server:
  port: 8761

spring:
  application:
    name: ead-service-registry

# Config to access the service registry
ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    register-with-eureka: false  # Dont register as Client
    fetch-registry: false # Don't search the own registry on eureka server
    service-url:  ## Configuring the credential on default-zone
      default-zone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
