server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE # lb = load balance
          predicates:
            - Path= /ead-authuser/**  # Everything that comes on this path will be to EAD-AUTHUSER-SERVICE
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE
          predicates:
              - Path= /ead-course/**  # Everything that comes on this path will be to EAD-COURSE-SERVICE
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost