server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: http://localhost:8087/
          predicates:
            - Path= /ead-authuser/**  # Everything that comes on this path will be to AuthUser-MS
        - id: course-service
          uri: http://localhost:8082/
          predicates:
              - Path= /ead-course/**  # Everything that comes on this path will be to Course-MS