server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/' # Default RequestMapping

spring: # Name of microservice when they are clients on eureka
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

# Log Level of Application
logging:
  level:
    com.ead: TRACE
    root: INFO # More details but not of Everything
    org.springframework.web: DEBUG # Log to see into the Requests
    org.hibernate: INFO  # Log to see the Hibernate

ead:
  api:
    url:
      course: 'http://ead-course-service'  # ID eureka ( application name)

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
      instance:
        hostname: localhost