
spring: # Name of microservice when they are clients on eureka
  application:
    name: ead-authuser-service
  config:                             # import: 'optional:configserver:'
    import: 'configserver:'  # "optional:" Allows the default configuration of authuser application.yml when our config-server is offline
  cloud:
    config:
      discovery:
        service-id: ead-config-server   # Target into config-server.. to be a config client
      username: configserver
      password: 'ead123cs'
