server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show_sql: true
  output:
      ansi:
        enabled: always
# Log Level of Application
logging:
      level:
        com.ead: TRACE
        root: INFO # More details but not of Everything
        org.springframework.web: DEBUG # Log to see into the Requests
        org.hibernate: INFO  # Log to see the Hibernate


ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
      instance:
        hostname:localhost