server:
  port: 8888 #Config server default port


spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pinhobrunodev/ead-config-server-repo
          default-label: master
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}

ead:
  configServer:
    username: configServer
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl: # Connecting Config Server into Service Registry (now with Authentication)
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

